export const SELECT_PIZZA_DOUGH = "SELECT_PIZZA_DOUGH";
export const SELECT_PIZZA_SIZE = "SELECT_PIZZA_SIZE";
export const ADD_PIZZA_TO_BASKET = "ADD_PIZZA_TO_BASKET";
export const SELECT_PIZZA_TAG = "SELECT_PIZZA_TAG";
export const RESET_PIZZA_TAG = "RESET_PIZZA_TAG";
